---
title: "Lab7 rankbased test"
author: "Ashley Stroud"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hello this Ashley, and I created this repo and markdown document. 

Collaborator(Kaitlyn)
Lets make some histograms!
```{r}

library(tidyverse)
kermit<- read_csv("kermit.csv")

kermit_hist<- ggplot(kermit, aes(x= Score.pre))+
  geom_histogram()+
  facet_wrap(~Gender)

kermit_hist
  
```

Creator: doing some rank-based tests

```{r}

# is there a significant difference in pre-talks kermit scores for males and females?

# unpaired data: Mann-Whitney U
# look at pre as a function of gender,  result is, cannot compute p value with ties, that is just saying...?

MwU_kermit <- kermit %>% 
  wilcox.test(Score.pre ~ Gender, data = .)

MwU_kermit

```

Collaborator(Kaitlyn)

Is there a significant difference in Kermit ranks for pre-talk and post-talk scores(ignoring all other variables)?


Null: There is no difference

```{r}

wsr_kermit <- wilcox.test(kermit$Score.pre, kermit$Score.post, paired=TRUE)
wsr_kermit

#There is no significant difference in Kermit rankings before and after his talk( then add in statistical summary...)
```















